inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/*'
    - 'bin/*'
    - 'log/*'
    - 'vendor/**/*'
    - 'docker/**/*'
    - 'frontend/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false