version: '3.9'
services:
  nginx:
    image: nginx:1.23-alpine
    platform: linux/x86_64
    ports:
      - "81:80"
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - vue
      - rails
  vue:
    image: node:18.1-alpine
    platform: linux/x86_64
    volumes:
      - ./frontend:/app:cached
    working_dir: /app
    command: "yarn dev"
  rails:
    build: ./docker/rails
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000"
    depends_on:
      - mysql
    environment:
      - APP_DOCKER_DB_HOST=mysql
      - APP_DOCKER_DB_PORT=3306
    stdin_open: true
    tty: true
  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_USER: appuser
      MYSQL_ROOT_PASSWORD: asf#aks3AFja
      MYSQL_PASSWORD: asf#aks3AFja
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_HOST: "%"
    stdin_open: true
    tty: true

volumes:
  mysql-data: