version: '3.9'

x-logging-configuration: &logging-configuration
  logging:
    driver: json-file
    options:
      max-size: 1m
      max-file: '3'

services:
  nginx:
    <<: *logging-configuration
    image: nginx:1.23-alpine
    platform: linux/x86_64
    ports:
      - "81:80"
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf.template
    depends_on:
      - vue
      - rails
    command: /bin/sh -c "envsubst '$$NGINX_PORT$$NGINX_SERVER_NAME' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && nginx -g 'daemon off;'"
    environment:
      NGINX_PORT: 80
      NGINX_SERVER_NAME: localhost
  vue:
    <<: *logging-configuration
    build: ./docker/vue
    volumes:
      - ./frontend:/app
    command: "yarn dev"
  rails:
    <<: *logging-configuration
    build: ./docker/rails
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mysql
      - redis
    environment:
      - APP_DOCKER_DB_HOST=mysql
      - APP_DOCKER_DB_PORT=3306
  mysql:
    <<: *logging-configuration
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      TZ: 'Asia/Tokyo'
  redis:
    <<: *logging-configuration
    image: redis:3.2
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio_123
      MINIO_ROOT_PASSWORD: pass_123
    ports:
      - '9000:9000'
      - '9001:9001'
    entrypoint: bash
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      /opt/bin/minio server /export --address :9000 --console-address :9001;
      "
    volumes:
      - ./minio/data:/data
      - ./minio/export:/export
      - ./minio/config:/root/.minio
      - ./minio/policies:/policies

volumes:
  mysql-data:
  rails-bundle: