version: '3.9'
services:
  nginx:
    image: nginx:1.23-alpine
    platform: linux/x86_64
    ports:
      - "81:80"
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - vue
      - rails
  vue:
    build: ./docker/vue
    volumes:
      - ./frontend:/app
    command: "yarn dev"
    stdin_open: true
  rails:
    build: ./docker/rails
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mysql
    environment:
      - APP_DOCKER_DB_HOST=mysql
      - APP_DOCKER_DB_PORT=3306
    stdin_open: true
    tty: true
  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      TZ: 'Asia/Tokyo'
    stdin_open: true
    tty: true

volumes:
  mysql-data: