version: '3.9'

x-logging-configuration: &logging-configuration
  logging:
    driver: json-file
    options:
      max-size: 1m
      max-file: '3'

services:
  nginx:
    <<: *logging-configuration
    build: ./docker/nginx
    ports:
      - "81:80"
    depends_on:
      - vue
      - rails
    environment:
      NGINX_PORT: '80'
      RAILS_HOST: 'rails'
      RAILS_PORT: '3000'
      VUE_HOST: 'vue'
      VUE_PORT: '3120'
  vue:
    <<: *logging-configuration
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/dist:/app/dist
    command: "yarn dev"
    environment:
      NODE_ENV: 'development'
  rails:
    <<: *logging-configuration
    build: .
    tty: true
    stdin_open: true
#    volumes:
#      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      REDIS_URL: 'redis://redis'
  mysql:
    <<: *logging-configuration
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
  redis:
    <<: *logging-configuration
    image: redis:3.2
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio_123
      MINIO_ROOT_PASSWORD: pass_123
    ports:
      - '9000:9000'
      - '9001:9001'
    entrypoint: sh -c "
      mkdir -p /export/manchat;
      mkdir -p /export/.minio.sys/buckets/manchat;
      minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./minio/data:/data
      - ./minio/export:/export
      - ./minio/config:/root/.minio
      - ./minio/policies:/policies

volumes:
  mysql-data:
  rails-bundle: