version: '3.9'
services:
  rails:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - app-public:/app/public
      - app-tmp:/app/tmp
      - app-log:/app/log
      - app-bundle:/app/.bundle
      - app-vendor-bundle:/app/vendor/bundle
    environment:
      - APP_DOCKER_DB_HOST=mysql
      - APP_DOCKER_DB_PORT=3306
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s"
    depends_on:
      - mysql
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_USER: appuser
      MYSQL_ROOT_PASSWORD: asf#aks3AFja
      MYSQL_PASSWORD: asf#aks3AFja
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_HOST: "%"
    tty: true
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password    
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  nginx:
    build: ./docker/nginx
    ports:
      - 81:80
    depends_on:
      - app
    volumes:
      - app-public:/app/public
      - app-tmp:/app/tmp

volumes:
  app-public:
  app-bundle:
  app-vendor-bundle:
  app-tmp:
  app-log:
  mysql-data: