version: '3.9'

x-logging-configuration: &logging-configuration
  logging:
    driver: json-file
    options:
      max-size: 1m
      max-file: '3'

services:
  nginx:
    <<: *logging-configuration
    build: ./docker/nginx
    ports:
      - "81:80"
    depends_on:
      - vue
      - rails
  vue:
    <<: *logging-configuration
    build: ./docker/vue
    volumes:
      - ./frontend:/app
    command: "yarn dev"
  rails:
    <<: *logging-configuration
    build: ./docker/rails
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mysql
      - redis
    environment:
      - APP_DOCKER_DB_HOST=mysql
      - APP_DOCKER_DB_PORT=3306
  mysql:
    <<: *logging-configuration
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      TZ: 'Asia/Tokyo'
  redis:
    <<: *logging-configuration
    image: redis:3.2
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio_123
      MINIO_ROOT_PASSWORD: pass_123
    ports:
      - '9000:9000'
      - '9001:9001'
    command: minio server /export --address :9000 --console-address :9001;
    volumes:
      - ./minio/data:/data
      - ./minio/export:/export
      - ./minio/config:/root/.minio
      - ./minio/policies:/policies
  minio-mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set my-minio http://minio:9000 minio_123 pass_123;
      mc mb my-minio/manchat;
      mc anonymous set download my-minio/manchat;
      exit 0;
      "

volumes:
  mysql-data:
  rails-bundle: